services:
  emby:
    container_name: emby
    network_mode: bridge
    image: lovechen/embyserver:4.7.14.0
    environment:
      - UID=1000
      - GID=1000
      - GIDLIST=0
    volumes:
      - /home/amtoaer/.config/nas/emby:/config
      - /home/amtoaer/Videos:/Videos
    ports:
      - 54319:8096
    devices:
      - /dev/dri:/dev/dri
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
